const MENU_DATA = [
  // ========== SOUPS - VEG ==========
  { id: 1, name: "Veg Corn Soup", category: "Soups", subcategory: "Veg Soups", type: "veg", price: 90, image: "Images/vegcorn Soup.jpg", description: "Sweet corn and crisp vegetables simmered in a light, nourishing broth. A perfect start to your meal.", serves: "1", spiceLevel: "mild", status: "available", badges: [] },
  { id: 2, name: "Veg Hot and Sour Soup", category: "Soups", subcategory: "Veg Soups", type: "veg", price: 100, image: "Images/veg hot and sour soup.jpg", description: "Tangy and spicy vegetable soup with vinegar and chilli — bold Indo-Chinese flavours in every sip.", serves: "1", spiceLevel: "medium", status: "available", badges: [] },
  { id: 3, name: "Lemon Coriander Soup", category: "Soups", subcategory: "Veg Soups", type: "veg", price: 100, image: "Images/lemon coriander soup.jpg", description: "Refreshing clear soup infused with lemon zest and fresh coriander. Light, tangy and wholesome.", serves: "1", spiceLevel: "mild", status: "available", badges: [] },
  { id: 4, name: "Tomato Soup", category: "Soups", subcategory: "Veg Soups", type: "veg", price: 110, image: "Images/tomato soup.jpg", description: "Rich and creamy tomato soup simmered with aromatic spices. A timeless classic.", serves: "1", spiceLevel: "mild", status: "available", badges: [] },
  { id: 5, name: "Veg Manchow Soup", category: "Soups", subcategory: "Veg Soups", type: "veg", price: 110, image: "Images/veg manchow soup.jpg", description: "Thick, spiced Indo-Chinese soup topped with crispy fried noodles. A crowd favourite.", serves: "1", spiceLevel: "medium", status: "available", badges: [] },
  // ========== SOUPS - NON VEG ==========
  { id: 6, name: "Chicken Corn Soup", category: "Soups", subcategory: "Non Veg Soups", type: "non-veg", price: 110, image: "Images/chicken corn soup.jpg", description: "Tender chicken shreds and sweet corn in a comforting, flavour-packed broth.", serves: "1", spiceLevel: "mild", status: "available", badges: [] },
  { id: 7, name: "Chicken Hot and Sour Soup", category: "Soups", subcategory: "Non Veg Soups", type: "non-veg", price: 120, image: "Images/chicken hot and soup.jpg", description: "Fiery and tangy chicken soup with bold Indo-Chinese flavours — warming and satisfying.", serves: "1", spiceLevel: "hot", status: "available", badges: [] },
  { id: 8, name: "Chicken Manchow Soup", category: "Soups", subcategory: "Non Veg Soups", type: "non-veg", price: 130, image: "Images/chicken manchow soup.jpg", description: "Classic thick manchow soup with juicy chicken pieces and crispy noodles on top.", serves: "1", spiceLevel: "medium", status: "available", badges: [] },
  { id: 9, name: "Chicken Silver Soup", category: "Soups", subcategory: "Non Veg Soups", type: "non-veg", price: 140, image: "Images/chicken sliver soup.jpg", description: "Light and delicate clear chicken soup, soothing and nourishing for the soul.", serves: "1", spiceLevel: "mild", status: "available", badges: [] },

  // ========== STARTERS - VEG ==========
  { id: 10, name: "Gobi 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 210, image: "Images/goby 65.jpg", description: "Crispy golden cauliflower florets tossed in a spicy South-Indian masala. Addictively crunchy.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 11, name: "Baby Corn Chilli", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/baby corn chilli.jpg", description: "Crunchy baby corn stir-fried with bell peppers, garlic and green chillies in Indo-Chinese style.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 12, name: "Gobi Manchurian", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 200, image: "Images/gobi manchurian.jpg", description: "Cauliflower florets in a sticky, tangy Manchurian sauce with spring onions and soy.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 13, name: "Baby Corn 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 300, image: "Images/baby corn 65.jpg", description: "Deep-fried baby corn coated in a spicy 65-style masala. Crispy outside, tender inside.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 14, name: "Golden Fried Baby Corn", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/golden fried baby corn.jpg", description: "Delicately battered baby corn fried to a perfect golden crunch. Light and delicious.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 15, name: "Baby Corn Majestic", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/baby corn majestic.jpg", description: "A Bangalore favourite — crispy baby corn tossed with yogurt, curry leaves and coconut.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 16, name: "Baby Corn Manchurian", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/baby corn manchurian.jpg", description: "Crispy baby corn tossed in a bold Manchurian gravy — a crowd-pleasing Indo-Chinese starter.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 17, name: "Paneer Manchurian", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 290, image: "Images/panner manchurian.jpg", description: "Fried paneer cubes coated in a rich, tangy Manchurian sauce with garlic and soy.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 18, name: "Paneer Chilli", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 180, image: "Images/panner chilli.jpg", description: "Succulent paneer cubes stir-fried with capsicum, onions and green chillies. A spicy delight.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 19, name: "Veg Chilli", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 180, image: "Images/veg chilli.jpg", description: "Mixed vegetables tossed in a fiery chilli sauce with capsicum and onions. Bold and vibrant.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 20, name: "Veg Manchurian", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 170, image: "Images/veg manchurian.jpg", description: "Crispy vegetable balls in a tangy, spiced Manchurian sauce. A vegetarian classic.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 21, name: "Paneer Tikka", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 240, image: "Images/panner tikka.jpg", description: "Marinated paneer cubes grilled in a tandoor with peppers and onions. Smoky, charred perfection.", serves: "1-2", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 22, name: "Aloo 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 130, image: "Images/aloo 65.jpg", description: "Crispy spiced potato bites in a tangy South-Indian masala. A budget-friendly favourite.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 23, name: "Veg 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 190, image: "Images/veg 65.jpg", description: "A medley of vegetables deep-fried in the iconic 65-style spicy coating. Crunchy and addictive.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 24, name: "Paneer 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 300, image: "Images/panner 65.jpg", description: "Soft paneer coated in a fiery 65-style masala and deep fried to golden perfection.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 25, name: "Paneer Majestic", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/panner majestic.jpg", description: "Paneer tossed in curd, coconut and curry leaves — the signature Bangalore Majestic style.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 26, name: "Mushroom Chilli", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/mushroom chilli.jpg", description: "Earthy mushrooms stir-fried in a spicy chilli sauce with capsicum and spring onions.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 27, name: "Mushroom Manchurian", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/mushroom manchurian.jpg", description: "Crispy mushroom pieces in a bold Manchurian gravy. Earthy, spicy and irresistible.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 28, name: "Mushroom 65", category: "Starters", subcategory: "Veg Starters", type: "veg", price: 320, image: "Images/mushroom 65.jpg", description: "Fresh mushrooms deep-fried in a spicy 65-style masala. A gourmet vegetarian starter.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== STARTERS - NON VEG (EGG) ==========
  { id: 29, name: "Egg Fry", category: "Starters", subcategory: "Non Veg Starters", type: "egg", price: 190, image: "Images/Egg Fry.jpg", description: "Classic pan-fried eggs seasoned with spices. Simple, satisfying and full of flavour.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 30, name: "Egg Manchurian", category: "Starters", subcategory: "Non Veg Starters", type: "egg", price: 190, image: "Images/Egg manchurian.jpg", description: "Fried eggs tossed in a tangy Indo-Chinese Manchurian sauce with garlic and soy.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 31, name: "Chilli Egg", category: "Starters", subcategory: "Non Veg Starters", type: "egg", price: 190, image: "Images/Chilli Egg.jpg", description: "Eggs stir-fried with green chillies, capsicum and onions in a fiery chilli sauce.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 32, name: "Egg 65", category: "Starters", subcategory: "Non Veg Starters", type: "egg", price: 190, image: "Images/Egg 65.jpg", description: "Boiled egg halves coated in a crispy, spiced 65-style batter. A unique and tasty starter.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== STARTERS - NON VEG (CHICKEN) ==========
  { id: 33, name: "Crispy Chicken Salt and Pepper", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 350, image: "Images/Crispy chicken salt and pepper.jpg", description: "Golden crispy chicken tossed with cracked black pepper and sea salt. Simple elegance.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 34, name: "Chicken Dry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 360, image: "Images/chicken dry.jpg", description: "Tender chicken pieces slow-cooked dry with whole spices and aromatic masalas.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 35, name: "Spicy Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 360, image: "Images/spicy chicken.jpg", description: "Fiery, marinated chicken pieces fried and tossed in a blazing spicy sauce. Handle with caution!", serves: "1-2", spiceLevel: "extra-hot", status: "available", badges: [] },
  { id: 36, name: "Chicken Tikka", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 260, image: "Images/chicken tikka.jpg", description: "Succulent chicken chunks marinated in yogurt and spices, chargrilled in a tandoor.", serves: "1-2", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 37, name: "Chilli Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/chilli chicken.jpg", description: "Crispy chicken tossed in a spicy Indo-Chinese chilli sauce. A restaurant all-time favourite.", serves: "1-2", spiceLevel: "hot", status: "available", badges: ["bestseller"] },
  { id: 38, name: "Murgh Malai Tikka", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 280, image: "Images/murgh malai tikka.jpg", description: "Creamy, melt-in-the-mouth chicken marinated in cashew cream and mild spices, grilled to perfection.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 39, name: "Chicken Chilli Kabab", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 280, image: "Images/chicken chilli kabab.jpg", description: "Minced chicken kababs blended with green chillies, herbs and spices, skewered and grilled.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 40, name: "Tandoori Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 450, image: "Images/tandoori chicken.jpg", description: "The classic whole chicken marinated overnight in yogurt and spices, roasted in a clay tandoor.", serves: "2-3", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 41, name: "Chicken Seekh Kabab", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 330, image: "Images/chicken seekh kabab.jpg", description: "Seasoned minced chicken shaped onto skewers, grilled over charcoal. Smoky and succulent.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 42, name: "Chicken Fry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 260, image: "Images/chicken fry.jpg", description: "Home-style fried chicken coated in a spiced batter — crispy skin, juicy inside.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 43, name: "Tawa Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 350, image: "Images/tawa ticken.jpg", description: "Chicken cooked on a flat iron tawa with butter, onions and a robust spice blend.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 44, name: "Garlic Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 350, image: "Images/garlic chicken.jpg", description: "Chicken pieces fried with an abundance of garlic and subtle spices. Intensely aromatic.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 45, name: "Chicken Chilli Coriander", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 350, image: "Images/chicken chilli coriander.jpg", description: "Chicken tossed with fresh coriander, green chillies and tangy spices. Fresh and fiery.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 46, name: "Lemon Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/lemon chicken.jpg", description: "Zesty lemon-marinated chicken with a bright, tangy flavour and crispy coating.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 47, name: "Pepper Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/pepper chicken.jpg", description: "Boldly spiced chicken with generous cracked black pepper and curry leaves. A South Indian classic.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 48, name: "Oil Fried Chicken Drumstick", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/oil fried chicken drumstick.jpg", description: "Juicy chicken drumsticks deep-fried until perfectly crispy. Great for grabbing with your hands.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 49, name: "Schezwan Lollipop", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 340, image: "Images/schezwan lollipop.jpg", description: "Chicken lollipops coated in fiery Schezwan sauce — a party favourite that packs a punch.", serves: "1-2", spiceLevel: "extra-hot", status: "available", badges: [] },
  { id: 50, name: "Chicken 555", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 290, image: "Images/chicken 555.jpg", description: "The famous 555 — crispy chicken in a signature spiced sauce. An iconic starter.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 51, name: "Ginger Chicken", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/ginger chicken.jpg", description: "Succulent chicken with a bold ginger punch, stir-fried with fresh herbs and spices.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 52, name: "Chicken Manchurian", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 280, image: "Images/chicken manchurian.jpg", description: "Crispy chicken balls in a dark, tangy Manchurian gravy. An Indo-Chinese masterpiece.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 53, name: "Chicken 65", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/chicken 65.jpg", description: "The iconic Chicken 65 — fiery, crispy, deep-fried chicken in a spiced yogurt marinade. Our most loved starter.", serves: "1-2", spiceLevel: "hot", status: "available", badges: ["bestseller"] },
  { id: 54, name: "Chicken Majestic", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 290, image: "Images/chicken majestic.jpg", description: "Crunchy fried chicken tossed in yogurt, coconut and curry leaves — the Bangalore Majestic style.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },

  // ========== STARTERS - NON VEG (MUTTON) ==========
  { id: 55, name: "Pepper Mutton", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 400, image: "Images/pepper mutton.jpg", description: "Tender mutton pieces dry-fried with bold black pepper and aromatic South Indian spices.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 56, name: "Mutton 65", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 400, image: "Images/mutton 65.jpg", description: "Juicy mutton in a blazing 65-style spicy coating. Rich, meaty and incredibly flavourful.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 57, name: "Chilli Mutton", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 400, image: "Images/chilli mutton.jpg", description: "Mutton stir-fried in a fiery chilli sauce with capsicum and onions. Bold and intense.", serves: "1-2", spiceLevel: "extra-hot", status: "available", badges: [] },
  { id: 58, name: "Telangana Mutton Fry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 420, image: "Images/telangana mutton fry.jpg", description: "Authentic Telangana-style dry mutton fry with raw onions, green chillies and regional spices. A true local gem.", serves: "1-2", spiceLevel: "extra-hot", status: "available", badges: ["bestseller"] },
  { id: 59, name: "Methi Mutton", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 420, image: "Images/methi mutton.jpg", description: "Succulent mutton cooked with fenugreek leaves and robust masalas. Earthy and aromatic.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 60, name: "Mutton Fry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 480, image: "Images/mutton fry.jpg", description: "Traditional dry mutton fry cooked with whole spices until perfectly caramelised. A feast.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== STARTERS - NON VEG (FISH & PRAWNS) ==========
  { id: 61, name: "Fish Manchurian", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 260, image: "Images/chilli fish.jpg", description: "Crispy fish pieces tossed in a tangy Manchurian sauce with garlic and soy.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 62, name: "Chilli Fish", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 260, image: "Images/chilli fish.jpg", description: "Fish fillets stir-fried with green chillies, capsicum and a fiery sauce. Fresh and zesty.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 63, name: "Apollo Fish", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 250, image: "Images/appollo fish.jpg", description: "The legendary Apollo Fish — crispy fried fish tossed in a creamy, mildly spiced sauce. A Hyderabad classic.", serves: "1-2", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 64, name: "Fish Fry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 200, image: "Images/fish fry.jpg", description: "Fresh fish marinated in turmeric and spices, shallow-fried to crispy, golden perfection.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 65, name: "Chilli Prawns", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/chilli prawns.jpg", description: "Juicy prawns tossed in a spicy chilli sauce with capsicum and garlic. Seafood lovers' delight.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 66, name: "Loose Prawns", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/loose prawns.jpg", description: "Fresh prawns cooked in a dry masala with whole spices. Simple, rustic and full of character.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 67, name: "Golden Fried Prawns", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/golden fried prawns.jpg", description: "Large prawns in a light, crispy batter fried to a gorgeous golden colour.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 68, name: "Prawns Fry", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 300, image: "Images/prawns fry.jpg", description: "Prawns marinated with Indian spices and pan-fried till beautifully done.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 69, name: "Ginger Prawns", category: "Starters", subcategory: "Non Veg Starters", type: "non-veg", price: 320, image: "Images/ginger prawns.jpg", description: "Fresh prawns cooked with generous ginger, green chillies and herbs. Aromatic and punchy.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== MAIN COURSE - VEG ==========
  { id: 70, name: "Methi Chaman", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/methi chaman.jpg", description: "Cottage cheese and spinach cooked with fenugreek and aromatic Punjabi spices. Hearty and wholesome.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 71, name: "Mushroom Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/mushroom masala.jpg", description: "Earthy mushrooms in a rich, spiced onion-tomato gravy. Goes beautifully with any bread.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 72, name: "Baby Corn Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/baby corn masala.jpg", description: "Tender baby corn in a flavourful masala gravy. A unique and satisfying vegetarian option.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 73, name: "Paneer Shahi Korma", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/panner shahi korma.jpg", description: "Paneer in a luxurious royal korma sauce with cashews, cream and mild spices. Regal and rich.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 74, name: "Palak Paneer", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 320, image: "Images/palak panner.jpg", description: "Creamy spinach puree with soft paneer cubes and warming spices. A timeless North Indian classic.", serves: "2", spiceLevel: "mild", status: "available", badges: ["bestseller"] },
  { id: 75, name: "Plain Palak", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 200, image: "Images/plain palak.jpg", description: "Fresh spinach prepared with garlic and mild spices. Healthy, nutritious and delicious.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 76, name: "Paneer Chatpata", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 200, image: "Images/panner chatpata.jpg", description: "Paneer in a tangy, spicy chatpata masala with a burst of flavours in every bite.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 77, name: "Kaju Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/kaju masala.jpg", description: "Cashew nuts in a rich, creamy masala gravy. A luxurious vegetarian treat.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 78, name: "Kaju Paneer", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 360, image: "Images/kaju panner.jpg", description: "Soft paneer and whole cashews in a smooth, mildly spiced cream-based gravy.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 79, name: "Paneer Tikka Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 290, image: "Images/panner tikka masala.jpg", description: "Grilled paneer tikka pieces simmered in a luscious tomato and cream gravy. An all-time favourite.", serves: "2", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 80, name: "Paneer Butter Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 230, image: "Images/panner butter masala.jpg", description: "Paneer in a velvety butter-tomato sauce. Mildly spiced and irresistibly creamy — a crowd pleaser.", serves: "2", spiceLevel: "mild", status: "available", badges: ["bestseller"] },
  { id: 81, name: "Aloo Gobi Masala", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 280, image: "Images/aloo gobi masala.jpg", description: "Potato and cauliflower cooked dry with turmeric and spices. Classic North Indian home-style.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 82, name: "Malai Kofta", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 300, image: "Images/malai kofta.jpg", description: "Soft cottage cheese and vegetable dumplings in a rich, creamy tomato gravy. Indulgent and elegant.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 83, name: "Veg Shahi Korma", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 280, image: "Images/Veg Shahi Korma.jpg", description: "Mixed vegetables in a rich royal korma sauce with cashew paste, cream and aromatic spices.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 84, name: "Veg Kofta", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 280, image: "Images/malai kofta.jpg", description: "Spiced vegetable dumplings cooked in a flavourful, tangy gravy. Hearty and satisfying.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 85, name: "Veg Chatpata", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 260, image: "Images/Veg Chatpata.jpg", description: "Mixed vegetables in a tangy, lively chatpata masala. Vibrant and full of punchy flavours.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 86, name: "Veg Kolhapuri", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 260, image: "Images/Veg Kolhapuri.jpg", description: "Fiery Kolhapuri-style vegetables in a bold, coconut-spiced gravy from Maharashtra.", serves: "2", spiceLevel: "extra-hot", status: "available", badges: [] },
  { id: 87, name: "Kadai Veg", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 230, image: "Images/Kadai veg.jpg", description: "Fresh vegetables stir-fried in a kadai with capsicum, tomatoes and whole spices.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 88, name: "Mix Veg Curry", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 220, image: "Images/Mix veg curry.jpg", description: "A wholesome medley of seasonal vegetables in a light, spiced curry gravy.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 89, name: "Dal Fry", category: "Main Course", subcategory: "Veg Main Course", type: "veg", price: 140, image: "Images/Dal Fry.jpg", description: "Creamy yellow lentils tempered with cumin, garlic and butter. The ultimate comfort food.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },

  // ========== MAIN COURSE - NON VEG ==========
  { id: 90, name: "Egg Burji", category: "Main Course", subcategory: "Non Veg Main Course", type: "egg", price: 90, image: "Images/Egg burji.jpg", description: "Scrambled eggs cooked with onions, tomatoes and spices. Simple, quick and satisfying.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 91, name: "Methi Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 320, image: "Images/methi chicken.jpg", description: "Chicken cooked with fresh fenugreek leaves and robust masalas. A restaurant specialty.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 92, name: "Murgh Musallam", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/murgh musallam.jpg", description: "A Mughal-era recipe — whole chicken slow-cooked in a regal blend of spices and aromatic gravy.", serves: "2-3", spiceLevel: "medium", status: "available", badges: [] },
  { id: 93, name: "Chicken Masala", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 280, image: "Images/chicken masala.jpg", description: "Tender chicken in a rich, spiced onion-tomato masala gravy. A hearty classic.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 94, name: "Andhra Chicken Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/andhra chicken curry.jpg", description: "Fiery Andhra-style chicken curry with red chillies and bold regional spices. Intensely flavourful.", serves: "2", spiceLevel: "extra-hot", status: "available", badges: [] },
  { id: 95, name: "Telangana Chicken Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/telangana chicken curry.jpg", description: "Authentic Telangana-style chicken curry with local spices and a rustic, home-cooked depth.", serves: "2", spiceLevel: "hot", status: "available", badges: ["bestseller"] },
  { id: 96, name: "Punjabi Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/punjabi chicken.jpg", description: "North Indian-style dhaba chicken with a bold, smoky masala gravy. Robust and satisfying.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 97, name: "Achari Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/achari chicken.jpg", description: "Chicken cooked with pickle spices — mustard, fennel and fenugreek for a tangy, bold flavour.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 98, name: "Chicken Afghani", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/chicken afghani.jpg", description: "Tender chicken in a creamy, mildly spiced white gravy with cashew and cream. Subtly rich.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 99, name: "Chicken Shahi Korma", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/chicken shahi korma.jpg", description: "Chicken in a royal korma sauce with saffron, nuts and cream. Mughal-inspired and luxurious.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 100, name: "Chicken Tikka Masala", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/chicken tikka masala.jpg", description: "Grilled chicken tikka in a rich, smoky tomato-cream gravy. Globally loved, locally perfected.", serves: "2", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 101, name: "Chicken Mughlai", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 280, image: "Images/chicken mughlai.jpg", description: "Chicken in a classic Mughal-style gravy with almonds, cream and delicate spices.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 102, name: "Kadai Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 280, image: "Images/kadai chicken.jpg", description: "Chicken cooked in a kadai with capsicum, onions and whole spices. Bold and aromatic.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 103, name: "Butter Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 260, image: "Images/butter chicken.jpg", description: "The iconic Butter Chicken — tender chicken in a velvety, mildly spiced tomato-butter sauce. A true legend.", serves: "2", spiceLevel: "mild", status: "available", badges: ["bestseller"] },
  { id: 104, name: "Dum Ka Chicken", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 240, image: "Images/dum ka chicken.jpg", description: "Chicken slow-cooked in a sealed pot (dum style) with fragrant spices. Deeply flavoured.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 105, name: "Chicken Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 220, image: "Images/chicken curry.jpg", description: "Classic home-style chicken curry with fresh masalas. Simple, comforting and full of love.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 106, name: "Mutton Shahi Korma", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 420, image: "Images/mutton shahi korma.jpg", description: "Rich and velvety mutton korma with cashew paste, cream and royal Mughal spices.", serves: "2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 107, name: "Mutton Keema Masala", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 420, image: "Images/mutton keema masala.jpg", description: "Minced mutton cooked with robust masalas and green peas. A hearty, flavour-packed dish.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 108, name: "Mutton Masala Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 380, image: "Images/mutton masala curry.jpg", description: "Slow-cooked mutton in a thick, spiced masala gravy. Rich, tender and deeply satisfying.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 109, name: "Mutton Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 360, image: "Images/mutton curry.jpg", description: "Traditional mutton curry with whole spices and a thin, flavourful broth. Wholesome and rustic.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 110, name: "Chepala Pulusu", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 320, image: "Images/chepala pulusu.jpg", description: "Authentic Andhra-style tangy fish curry cooked with tamarind, tomatoes and fiery spices. A regional jewel.", serves: "2", spiceLevel: "hot", status: "available", badges: ["bestseller"] },
  { id: 111, name: "Fish Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 300, image: "Images/fish curry.jpg", description: "Fresh fish in a spiced coconut-tomato curry. Light, flavourful and wonderful with rice.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 112, name: "Prawns Curry", category: "Main Course", subcategory: "Non Veg Main Course", type: "non-veg", price: 390, image: "Images/prawns curry.jpg", description: "Succulent prawns in a richly spiced masala curry. A seafood lover's dream.", serves: "2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== BREADS ==========
  { id: 113, name: "Methi Paratha", category: "Breads", subcategory: "Breads", type: "veg", price: 60, image: "Images/methi paratha.jpg", description: "Whole wheat flatbread with fresh fenugreek leaves and spices. Nutritious and flavoursome.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 114, name: "Butter Paratha", category: "Breads", subcategory: "Breads", type: "veg", price: 60, image: "Images/butter paratha.jpg", description: "Crispy layered paratha made with butter. Flaky, golden and simply delicious.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 115, name: "Laccha Paratha", category: "Breads", subcategory: "Breads", type: "veg", price: 60, image: "Images/laccha paratha.jpg", description: "Multi-layered, flaky whole wheat paratha. Each layer is thin, crispy and buttery.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 116, name: "Plain Naan", category: "Breads", subcategory: "Breads", type: "veg", price: 40, image: "Images/plain naan.jpg", description: "Soft, fluffy tandoor-baked naan. The perfect companion for any curry.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 117, name: "Butter Naan", category: "Breads", subcategory: "Breads", type: "veg", price: 45, image: "Images/butter naan.jpg", description: "Freshly baked naan brushed generously with butter. Soft, warm and irresistible.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 118, name: "Garlic Naan", category: "Breads", subcategory: "Breads", type: "veg", price: 55, image: "Images/garlic naan.jpg", description: "Naan topped with roasted garlic and fresh coriander. Aromatic and absolutely divine.", serves: "1", spiceLevel: "none", status: "available", badges: ["bestseller"] },
  { id: 119, name: "Kothmir Roti", category: "Breads", subcategory: "Breads", type: "veg", price: 35, image: "Images/kothmir roti.jpg", description: "Thin whole wheat roti with fresh coriander. Light, soft and perfect for daily meals.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 120, name: "Butter Tandoori Roti", category: "Breads", subcategory: "Breads", type: "veg", price: 35, image: "Images/butter tandoori roti.jpg", description: "Classic tandoor-cooked roti topped with butter. Slightly charred and wonderfully soft.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 121, name: "Tandoori Roti", category: "Breads", subcategory: "Breads", type: "veg", price: 30, image: "Images/tandoori roti.jpg", description: "Traditional whole wheat roti baked in a clay tandoor. Rustic, healthy and flavourful.", serves: "1", spiceLevel: "none", status: "available", badges: [] },
  { id: 122, name: "Rumali Roti", category: "Breads", subcategory: "Breads", type: "veg", price: 20, image: "Images/rumali roti.jpg", description: "Paper-thin handkerchief bread, soft as a cloth. Pairs beautifully with any rich curry.", serves: "1", spiceLevel: "none", status: "available", badges: [] },

  // ========== RICE & BIRYANI ==========
  { id: 123, name: "Curd Rice", category: "Rice & Biryani", subcategory: "Rice", type: "veg", price: 110, image: "Images/curd rice.jpg", description: "Cooling, creamy curd rice tempered with curry leaves, mustard and green chillies. A South Indian staple.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 124, name: "Veg Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "veg", price: 630, image: "Images/veg Biryani.jpg", description: "Fragrant basmati rice layered with seasonal vegetables and dum-cooked with saffron and whole spices.", serves: "2-3", spiceLevel: "medium", status: "available", badges: [] },
  { id: 125, name: "Chicken Dum Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 196, image: "Images/chicken dum Biryani.jpg", description: "Aromatic basmati layered with tender chicken, cooked sealed (dum style) to lock in every flavour.", serves: "1", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 126, name: "Boneless Chicken Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 280, image: "Images/boneless chicken Biryani.jpg", description: "Fragrant biryani made with boneless chicken pieces — no bones, all flavour.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 127, name: "Chicken 65 Piece Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 280, image: "Images/chicken 65 piece Biryani.jpg", description: "Aromatic biryani topped with crispy Chicken 65 pieces. The best of two worlds.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 128, name: "Chicken Fry Piece Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 280, image: "Images/chicken fry piece Biryani.jpg", description: "Biryani served with fried chicken pieces on top. Crispy, flavourful and filling.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 129, name: "Chicken Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 699, image: "Images/chicken Biryani.jpg", description: "Our signature family chicken biryani — slow-cooked with aromatic spices, saffron and whole masalas.", serves: "3-4", spiceLevel: "medium", status: "available", badges: ["bestseller"] },
  { id: 130, name: "Chicken 65 Biryani (Family Pack)", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 839, image: "Images/chicken 65 biryani(Family pack).jpg", description: "A generous family-sized biryani topped with Chicken 65. Perfect for celebrations and gatherings.", serves: "4-5", spiceLevel: "hot", status: "available", badges: [] },
  { id: 131, name: "Mutton Keema Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 350, image: "Images/mutton keema Biryani.jpg", description: "Fragrant basmati cooked with spiced minced mutton. Rich, meaty and deeply satisfying.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 132, name: "Boneless Mutton Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 630, image: "Images/boneless mutton Biryani.jpg", description: "Slow-dum-cooked biryani with succulent boneless mutton. Pure biryani bliss.", serves: "2-3", spiceLevel: "hot", status: "available", badges: [] },
  { id: 133, name: "Fish Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 490, image: "Images/fish Biryani.jpg", description: "Aromatic biryani with marinated fish and coastal spices. Fresh, unique and flavour-packed.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 134, name: "Prawns Biryani", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 532, image: "Images/prawns Biryani.jpg", description: "Juicy prawns layered with saffron rice and dum-cooked to aromatic perfection.", serves: "2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 135, name: "Chicken Dum Biryani (Mini)", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 358, image: "Images/chicken dum biryani(mini).jpg", description: "All the magic of our Chicken Dum Biryani in a personal-sized portion. Perfect for one.", serves: "1", spiceLevel: "medium", status: "available", badges: [] },
  { id: 136, name: "Chicken 65 Biryani (Mini)", category: "Rice & Biryani", subcategory: "Biryani", type: "non-veg", price: 358, image: "Images/chicken 65 Biryani(Mini).jpg", description: "Personal-sized Chicken 65 Biryani — crispy chicken on top of fragrant rice. Mini but mighty.", serves: "1", spiceLevel: "hot", status: "available", badges: [] },

  // ========== FRIED RICE - VEG ==========
  { id: 137, name: "Paneer Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 200, image: "Images/Panner Fried Rice.jpg", description: "Fluffy fried rice tossed with soft paneer cubes and vegetables in Indo-Chinese style.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 138, name: "Kaju Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 180, image: "Images/kaju Fried Rice.jpg", description: "Fragrant fried rice studded with crunchy cashews and seasonal vegetables.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 139, name: "Tomato Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 140, image: "Images/tomato fried rice.jpg", description: "Tangy tomato-flavoured fried rice with vegetables and spices. Light and vibrant.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 140, name: "Jeera Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 180, image: "Images/jeera fried rice.jpg", description: "Simple, aromatic cumin-flavoured rice. A subtle, earthy delight.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 141, name: "Veg Schezwan Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 180, image: "Images/veg schezwan fried rice.jpg", description: "Spicy Schezwan sauce tossed with fried rice and crunchy vegetables. Fiery Indo-Chinese.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 142, name: "Veg Manchurian Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 160, image: "Images/veg manchurian fried rice.jpg", description: "Fried rice topped with veggie manchurian balls in a tangy sauce. Two favourites in one.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 143, name: "Veg Soft Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 140, image: "Images/veg soft fried rice.jpg", description: "Lightly seasoned soft fried rice with vegetables. Mild and easy on the palate.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 144, name: "Veg Fried Rice", category: "Fried Rice & Noodles", subcategory: "Veg Fried Rice", type: "veg", price: 120, image: "Images/veg fried rice.jpg", description: "Classic vegetable fried rice with soy sauce and spring onions. A timeless Indo-Chinese staple.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },

  // ========== FRIED RICE - NON VEG ==========
  { id: 145, name: "Egg Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "egg", price: 120, image: "Images/Egg Fried Rice.jpg", description: "Fluffy fried rice tossed with scrambled eggs, soy sauce and spring onions.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 146, name: "Egg Soft Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "egg", price: 160, image: "Images/Egg Soft Fried Rice.jpg", description: "Lightly seasoned soft fried rice with eggs. Gentle flavour, satisfying texture.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 147, name: "Egg Schezwan Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "egg", price: 180, image: "Images/Egg schezwan Fried Rice.jpg", description: "Spicy Schezwan-style fried rice with eggs and crunchy vegetables.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 148, name: "Chicken Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "non-veg", price: 160, image: "Images/chicken Fried Rice.jpg", description: "Classic chicken fried rice with vegetables and soy. Satisfying and flavour-packed.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 149, name: "Chicken Soft Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "non-veg", price: 180, image: "Images/chicken soft fried rice.jpg", description: "Lightly seasoned chicken fried rice. Soft texture, mild flavour — great for all ages.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 150, name: "Chicken Schezwan Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "non-veg", price: 200, image: "Images/chicken schezwan fried rice.jpg", description: "Fiery Schezwan fried rice with chicken. Bold, spicy and intensely satisfying.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 151, name: "Chicken Chilli Garlic Fried Rice", category: "Fried Rice & Noodles", subcategory: "Non Veg Fried Rice", type: "non-veg", price: 220, image: "Images/chicken chilli garlic fried rice.jpg", description: "Chicken fried rice loaded with garlic and green chillies. Punchy, aromatic and delicious.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },

  // ========== NOODLES - VEG ==========
  { id: 152, name: "Veg Mix Noodles", category: "Fried Rice & Noodles", subcategory: "Veg Noodles", type: "veg", price: 210, image: "Images/Veg Mix Noodles.jpg", description: "A mix of noodle styles tossed with fresh vegetables and Indo-Chinese sauces.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 153, name: "Veg Manchurian Noodles", category: "Fried Rice & Noodles", subcategory: "Veg Noodles", type: "veg", price: 180, image: "Images/Veg manchurian Noodles.jpg", description: "Noodles tossed with tangy manchurian sauce and crispy vegetable balls.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 154, name: "Veg Soft Noodles", category: "Fried Rice & Noodles", subcategory: "Veg Noodles", type: "veg", price: 120, image: "Images/Veg Soft Noodles.jpg", description: "Gently seasoned soft noodles with vegetables. Light and easy to enjoy.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 155, name: "Veg Noodles", category: "Fried Rice & Noodles", subcategory: "Veg Noodles", type: "veg", price: 120, image: "Images/Veg Noodles.jpg", description: "Classic vegetable hakka noodles with soy sauce and spring onions. A quick, satisfying meal.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },

  // ========== NOODLES - NON VEG ==========
  { id: 156, name: "Egg Schezwan Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "egg", price: 150, image: "Images/Egg schezwan Noodles.jpg", description: "Spicy Schezwan egg noodles with bold Indo-Chinese flavours.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 157, name: "Egg Soft Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "egg", price: 150, image: "Images/Egg soft Noodles.jpg", description: "Soft, lightly seasoned egg noodles. Comforting and mild.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 158, name: "Egg Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "egg", price: 140, image: "Images/egg Noodles.jpg", description: "Classic egg hakka noodles tossed with soy and vegetables. Simple and satisfying.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] },
  { id: 159, name: "Chicken Schezwan Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "non-veg", price: 200, image: "Images/chicken schezwan noodles.jpg", description: "Fiery Schezwan chicken noodles. Bold, spicy and utterly addictive.", serves: "1-2", spiceLevel: "hot", status: "available", badges: [] },
  { id: 160, name: "Chicken Soft Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "non-veg", price: 180, image: "Images/chicken soft noodles.jpg", description: "Gently seasoned chicken noodles. Soft, mild and perfect for all tastes.", serves: "1-2", spiceLevel: "mild", status: "available", badges: [] },
  { id: 161, name: "Chicken Noodles", category: "Fried Rice & Noodles", subcategory: "Non Veg Noodles", type: "non-veg", price: 160, image: "Images/chicken noodles.jpg", description: "Classic chicken hakka noodles with soy sauce, spring onions and crunchy vegetables.", serves: "1-2", spiceLevel: "medium", status: "available", badges: [] }
];

// Default categories that ship with the menu (display order matters).
const DEFAULT_CATEGORIES = ['Soups', 'Starters', 'Main Course', 'Breads', 'Rice & Biryani', 'Fried Rice & Noodles'];

// All categories = defaults + owner-added custom categories.
function getAllCategories() {
  const custom = (typeof DB !== 'undefined') ? DB.getCustomCategories() : [];
  return [...DEFAULT_CATEGORIES, ...custom];
}

// Menu with owner edits/availability/badges/custom-items applied (reads live DB cache).
function getMenuWithOverrides() {
  const overrides = (typeof DB !== 'undefined') ? DB.getOverrides() : {};
  const customItems = (typeof DB !== 'undefined') ? DB.getCustomItems() : [];

  const applyOverride = item => {
    const o = overrides[item.id];
    return o ? { ...item, ...o } : item;
  };

  const base = MENU_DATA.map(applyOverride).filter(i => !i.deleted);
  const custom = customItems.map(applyOverride).filter(i => !i.deleted);
  return [...base, ...custom];
}

// Thin wrappers so older calls keep working, now backed by the shared DB layer.
function saveMenuOverride(id, changes) { DB.saveMenuOverride(id, changes); }
function getOrders() { return DB.getOrders(); }
function saveOrder(order) { DB.saveOrder(order); }
